/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package food.ordering.system.CustomerGUI;

import food.ordering.system.Location;
import food.ordering.system.VendorGUI.Vendor;

/**
 *
 * @author LENOVO
 */
public class VendorPanel extends javax.swing.JPanel {
    private Vendor vendor;
    private Customer customer;
    
    public VendorPanel(Vendor vendor, Customer customer) {
        initComponents();
        this.vendor = vendor;
        this.customer = customer;
        
        vendorName.setText(vendor.getName());
        vendorRating.setText(Double.toString((double) vendor.getRating()));
        vendorCategory.setText(vendor.getCategory());
        vendorAddress.setText(vendor.getAddress());
        
        calculateDistance(customer.getAddress().trim().toLowerCase(), vendor.getAddress().trim().toLowerCase());
    }
    
    public void calculateDistance(String customerAddress, String vendorAddress) {
        Location customerLocation = Location.locationMap.get(customerAddress);
        Location vendorLocation = Location.locationMap.get(vendorAddress);

        if (customerLocation != null && vendorLocation != null) {
            double vendorDistance = Location.calculateDistance(customerLocation,vendorLocation);

            distance.setText(Double.toString((double)vendorDistance)+"km");
        } else {
            System.out.println("Unknown location");
        }
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     **/
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        vendorImage = new javax.swing.JLabel();
        vendorName = new javax.swing.JLabel();
        vendorRating = new javax.swing.JLabel();
        vendorCategory = new javax.swing.JLabel();
        distance = new javax.swing.JLabel();
        vendorAddress = new javax.swing.JLabel();
        orderButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(500, 100));
        jPanel1.setMinimumSize(new java.awt.Dimension(500, 100));
        jPanel1.setPreferredSize(new java.awt.Dimension(500, 100));

        vendorImage.setText("IMG");

        vendorName.setText("Restaurant Name");

        vendorRating.setText("Ratings");

        vendorCategory.setText("Category");

        distance.setText("Distance from user");

        vendorAddress.setText("Location");

        orderButton.setText("Order");
        orderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(vendorImage)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(vendorName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(vendorAddress)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(vendorCategory)
                                    .addComponent(distance))))
                        .addContainerGap(261, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(vendorRating)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderButton)
                        .addGap(22, 22, 22))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(vendorImage))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(vendorName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vendorRating)
                            .addComponent(vendorCategory)
                            .addComponent(orderButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vendorAddress)
                            .addComponent(distance))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void orderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderButtonActionPerformed
        Menu vendorMenu = new Menu(vendor);
        vendorMenu.setVisible(true);
    }//GEN-LAST:event_orderButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel distance;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton orderButton;
    private javax.swing.JLabel vendorAddress;
    private javax.swing.JLabel vendorCategory;
    private javax.swing.JLabel vendorImage;
    private javax.swing.JLabel vendorName;
    private javax.swing.JLabel vendorRating;
    // End of variables declaration//GEN-END:variables
}
